# fly.toml file generated for grad-descent on 2021-04-12T20:17:32+02:00

app = "grad-descent"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builtin = "python"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 2
    soft_limit = 1

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    port = "8080"
    restart_limit = 6
    timeout = "2s"
